[package]
name = "midilab-io"
description = "I/O handling for the midilab editors"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
midilab.workspace = true
midi-io = { workspace = true, features = ["io"] }
tokio.workspace = true
