[package]
name = "nektar_impact_lx_plus_editor"
description = "GUI application for programming Nektar Impact LX+ controllers via Sysex"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "nektar_impact_lx_plus_editor"
path = "src/main.rs"

[dependencies]
dirs.workspace = true
eframe.workspace = true
midilab.workspace = true
midi-io = { workspace = true, features = ["io"] }
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
