[package]
name = "midilab-sim"
description = "Midi controller device simulation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck.workspace = true
midilab.workspace = true
midi-io.workspace = true
thiserror.workspace = true
tokio.workspace = true
