[package]
name = "midilab-editor"
description = "GUI application for programming midi controllers via Sysex"
categories = ["multimedia::audio", "hardware-support", "gui"]
keywords = ["midi", "sysex", "music", "editor", "hardware"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "midilab"
path = "src/main.rs"

[lib]
name = "midilab_editor"
crate-type = ["cdylib", "rlib"]

[dependencies]
midilab.workspace = true
midilab-gui.workspace = true
midilab-io.workspace = true

eframe.workspace = true
midir.workspace = true
tokio.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "HtmlCanvasElement",
    "MidiAccess",
    "MidiOptions",
] }
futures-timer.workspace = true
js-sys.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
