[package]
name = "arturia_minilab_mk2_editor"
description = "GUI application for programming Arturia MiniLab mkII via Sysex"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "arturia_minilab_mk2_editor"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
dirs.workspace = true
eframe.workspace = true
midilab.workspace = true
midilab-io.workspace = true
midi-io = { workspace = true, features = ["io"] }
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
