[package]
name = "midilab"
description = "Sysex deserialization and midi controller programming library"
categories = ["multimedia::audio", "hardware-support"]
keywords = ["midi", "sysex", "mpd226", "akai", "music"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck.workspace = true
enumeric.workspace = true
midi-io.workspace = true
num_enum.workspace = true
sanitize-filename = "0.6"
strum_macros.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
midi-io = { workspace = true, features = ["io"] }
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }
